[theme]
base="dark"
primaryColor="#aa80f7"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"


[browser]
gatherUsageStats = false

[server]
showEmailPrompt = false
port = 1337
